@startuml
skinparam linetype ortho
hide empty members
'skinparam groupInheritance 2
left to right direction

 namespace SwipeFeast.API.Controllers{

    /'BaseController'/
    class BaseController{
        +BaseController(IGroupService groupService, ILogger logger)
        {Field} -IGroupService _groupService
        {Field} -ILogger _logger
    }

    /''/
    class GroupController extends BaseController{
        +async Task<IActionResult> CreateGroup([FromBody] GroupCreationDto group)
        +IActionResult GetGroup([FromRoute] Guid groupId)
        +IActionResult JoinMember([FromRoute] int joinCode)
        +IActionResult LeaveMember([FromRoute] Guid groupId)     
    }
    
    /''/
    class FilterController extends BaseController{
        +IActionResult Get([FromRoute] Guid groupId)
        +IActionResult Patch([FromRoute] Guid groupId, [FromBody] List<Filter> filters)
        +IActionResult GetDefaultFilters()
    }

    /''/
    class RestauranteController extends BaseController{
        +IActionResult GetRestaurants([FromRoute] Guid groupId)
        +IActionResult GetRestaurant([FromRoute] Guid groupId, [FromRoute] string restaurantId)
        +IActionResult LikeRestaurant([FromRoute] Guid groupId, [FromRoute] string restaurantId)
    }

    /''/
    class RankingController extends BaseController{
        +IActionResult GetListOfRankings([FromRoute] Guid groupId)
    }

}

@enduml